certificatesResolvers: # letsEncrypt
  staging:
    acme: &staging_anchor
      email: anklav24@gmail.com  # TODO: Change this to your email
      storage: /ssl-certs/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: http
  production:
    acme:
      <<: *staging_anchor
      caServer: "https://acme-v02.api.letsencrypt.org/directory"

global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: common  # common, json, logfmt
  filePath: /var/log/traefik/traefik.log

accesslog:
 format: common  # common, json, logfmt
 filePath: /var/log/traefik/access.log

api:
  dashboard: true  # true by default

ping:
  entryPoint: ping

entryPoints:
  http:
    address: ":80"
    http:
     redirections:
       entryPoint:
         to: https
         scheme: https
  https:
    address: ":443"
  ping:
    address: ":8082"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /etc/traefik/tls.yaml
